services:
  email_reader:
    container_name: email-api
    image: appsuptime:email-reader
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./src:/app/src
    env_file:
      - .env
